name = "ContentPilot AI Dev"
client_id = "433cf493223c0c6b95bdb91b0de5961a"
application_url = "https://shopify-ai-text-manager-development.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_legal_policies,write_legal_policies,read_locales,read_online_store_navigation,read_online_store_pages,write_online_store_pages,read_product_listings,read_products,write_products,read_content,write_content,read_themes,write_themes,read_translations,write_translations,write_metaobjects,read_metaobject_definitions"

[auth]
redirect_urls = [
  "https://shopify-ai-text-manager-development.up.railway.app/auth/callback",
  "https://shopify-ai-text-manager-development.up.railway.app/auth/shopify/callback",
  "https://shopify-ai-text-manager-development.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/webhooks/compliance"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "8c19f3-ce.myshopify.com"
